name: Rust CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Formatting
      run: cargo fmt -- --check
    - name: Linting
      run: cargo clippy
      # Clippy is confused let's disabled it for now
      # run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
